server:
  port: 8081

spring:
  profiles:
    active: kdgc
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.p6spy.engine.spy.P6SpyDriver
    url: ${DATA_ROOM_DB_URL:jdbc:p6spy:mysql://127.0.0.1:3306/dataroom?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai}
    username: ${DATA_ROOM_DB_USER:root'}
    password: ${DATA_ROOM_DB_PWD:123456}

# 接口文档配置
knife4j:
  # 开启增强配置
  enable: true
  basic:
    # 是否开启认证
    enable: false
    # 证用户名
    username: admin
    # 认证密码
    password: dataRoom
  setting:
    enable-footer: false

data-room:
  apiUrl: ${DATA_ROOM_RESOURCE_PATH:D:/dataRoom}