dataroom:
  # 用户列表
  userList:
    - username: admin
      realName: 管理员
      tenantCode: default
      password: <PASSWORD>
      # 状态，可选值: normal: 正常，disabled: 禁用
      state: normal
      # 角色列表，可选值: manager： 管理员, developer:开发者, sharer:分享者
      roleCodeList: [ manager,developer,sharer ]
    - username: developer
      realName: 开发者
      tenantCode: default
      password: <PASSWORD>
      state: normal
      roleCodeList: [ developer,sharer ]
    - username: sharer
      # 用于分享使用、用户名不可改变
      realName: 分享者
      tenantCode: default
      password: <PASSWORD>
      state: normal
      roleCodeList: [ sharer ]

# 接口文档配置
knife4j:
  # 开启增强配置
  enable: true
  basic:
    # 是否开启认证
    enable: false
    # 证用户名
    username: admin
    # 认证密码
    password: dataRoom
  setting:
    enable-footer: false

springdoc:
  # 解决实体本身默认会解析为参数问题 https://doc.xiaominfo.com/docs/faq/v4/knife4j-parameterobject-flat-param
  default-flat-param-object: true
  group-configs:
    # 项目上自定义的包名可以配置多个
    - group: 'DataRoom'
      paths-to-match: '/**'
      # 扫描的包、可以配置多个
      packages-to-scan:
        - com.gccloud.gcpaas