server:
  port: 8081

spring:
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: classpath:/static/
      suffix: .html
  web:
    resources:
      add-mappings: true
      static-locations: classpath:/static/,classpath:/META-INF/resources/,classpath:/META-INF/resources/webjars/,file:${dataroom.resource.basePath},file:${dataroom.resource.uiPath}
  profiles:
    active: kdgc
    include: base
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${DATA_ROOM_DB_URL:jdbc:mysql://127.0.0.1:3306/dataroom?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai}
    username: ${DATA_ROOM_DB_USER:root'}
    password: ${DATA_ROOM_DB_PWD:123456}
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

