server:
  port: 8081

spring:
  profiles:
    active: kdgc
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.p6spy.engine.spy.P6SpyDriver
    url: ${DATA_ROOM_DB_URL:jdbc:p6spy:mysql://127.0.0.1:3306/dataroom?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai}
    username: ${DATA_ROOM_DB_USER:root'}
    password: ${DATA_ROOM_DB_PWD:123456}

# 接口文档配置
knife4j:
  # 开启增强配置
  enable: true
  basic:
    # 是否开启认证
    enable: false
    # 证用户名
    username: admin
    # 认证密码
    password: dataRoom
  setting:
    enable-footer: false

springdoc:
  # 解决实体本身默认会解析为参数问题 https://doc.xiaominfo.com/docs/faq/v4/knife4j-parameterobject-flat-param
  default-flat-param-object: true
  group-configs:
    # 项目上自定义的包名可以配置多个
    - group: 'DataRoom'
      paths-to-match: '/**'
      # 扫描的包、可以配置多个
      packages-to-scan:
        - com.gccloud.gcpaas

data-room:
  apiUrl: ${DATA_ROOM_RESOURCE_PATH:D:/dataRoom}